name: Unit-test & Coverage

on:
  push:
    branches:
      - master

jobs:
  cov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use node
        uses: actions/setup-node@master
        with:
          node-version: 12.8

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm run test  

      - name: Coverage
        run: npm run cov

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}